# Generated by Django 2.2.8 on 2020-12-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='about')),
            ],
            options={
                'db_table': 'about',
                'managed': False,
            },
        ),
    ]
